/**
 * Datos de prueba (mock) para desarrollo y testing
 * Cuando el backend real esté disponible, estos se reemplazan con datos reales
 */

export const MOCK_USERS = [
  {
    id: 0,
    firstName: 'Super',
    lastName: 'Admin',
    email: 'superadmin@lobbysync.com',
    username: 'superadmin',
    role: 'SUPER_ADMIN',
    status: 'active',
    phone: '+1234567889',
  },
  {
    id: 1,
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@lobbysync.com',
    username: 'admin',
    role: 'ADMIN',
    status: 'active',
    phone: '+1234567890',
  },
  {
    id: 2,
    firstName: 'Concierge',
    lastName: 'Staff',
    email: 'concierge@lobbysync.com',
    username: 'concierge',
    role: 'CONCIERGE',
    status: 'active',
    phone: '+1234567891',
  },
  {
    id: 3,
    firstName: 'Resident',
    lastName: 'One',
    email: 'resident@lobbysync.com',
    username: 'resident',
    role: 'RESIDENT',
    status: 'active',
    phone: '+1234567892',
  },
  {
    id: 4,
    firstName: 'María',
    lastName: 'López',
    email: 'maria@lobbysync.com',
    username: 'maria.lopez',
    role: 'ADMIN',
    status: 'active',
    phone: '+1234567893',
  },
  {
    id: 5,
    firstName: 'Luis',
    lastName: 'Torres',
    email: 'luis@lobbysync.com',
    username: 'luis.torres',
    role: 'CONCIERGE',
    status: 'pending',
    phone: '+1234567894',
  },
];

export const MOCK_BUILDINGS = [
  {
    id: 1,
    name: 'Torre Norte',
    address: 'Calle Principal 123',
    floors: 8,
    totalUnits: 32,
    manager: 'Juan Pérez',
  },
  {
    id: 2,
    name: 'Torre Central',
    address: 'Calle Principal 125',
    floors: 12,
    totalUnits: 48,
    manager: 'María González',
  },
  {
    id: 3,
    name: 'Torre Sur',
    address: 'Calle Principal 127',
    floors: 10,
    totalUnits: 40,
    manager: 'Carlos Ramírez',
  },
];

export const MOCK_UNITS = [
  {
    id: 1,
    unitId: 1,
    number: '101',
    buildingId: 1,
    floor: 1,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Juan Pérez',
    ownerEmail: 'juan.perez@email.com',
    ownerPhone: '+56912345678',
    ownerId: '12.345.678-9',
    resident: 'Juan Pérez',
    tenantName: 'Juan Pérez',
    monthlyFee: 150000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 2,
    unitId: 2,
    number: '102',
    buildingId: 1,
    floor: 1,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'María González',
    ownerEmail: 'maria.gonzalez@email.com',
    ownerPhone: '+56987654321',
    resident: 'María González',
    tenantName: 'María González',
    monthlyFee: 150000,
    pendingMonths: 1,
    balance: -150000,
  },
  {
    id: 3,
    unitId: 3,
    number: '201',
    buildingId: 1,
    floor: 2,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Carlos López',
    ownerEmail: 'carlos.lopez@email.com',
    ownerPhone: '+56911223344',
    resident: 'Carlos López',
    tenantName: 'Carlos López',
    monthlyFee: 150000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 4,
    unitId: 4,
    number: '202',
    buildingId: 1,
    floor: 2,
    status: 'available',
    occupancyStatus: 'available',
    monthlyFee: 150000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 5,
    unitId: 5,
    number: '101',
    buildingId: 2,
    floor: 1,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Ana Martínez',
    ownerEmail: 'ana.martinez@email.com',
    ownerPhone: '+56955667788',
    resident: 'Ana Martínez',
    tenantName: 'Ana Martínez',
    monthlyFee: 180000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 6,
    unitId: 6,
    number: '102',
    buildingId: 2,
    floor: 1,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Pedro Sánchez',
    ownerEmail: 'pedro.sanchez@email.com',
    ownerPhone: '+56944556677',
    resident: 'Pedro Sánchez',
    tenantName: 'Pedro Sánchez',
    monthlyFee: 180000,
    pendingMonths: 2,
    balance: -360000,
  },
  {
    id: 7,
    unitId: 7,
    number: '201',
    buildingId: 2,
    floor: 2,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Laura Fernández',
    ownerEmail: 'laura.fernandez@email.com',
    ownerPhone: '+56933445566',
    resident: 'Laura Fernández',
    tenantName: 'Laura Fernández',
    monthlyFee: 180000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 8,
    unitId: 8,
    number: '202',
    buildingId: 2,
    floor: 2,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Roberto Castro',
    ownerEmail: 'roberto.castro@email.com',
    ownerPhone: '+56922334455',
    resident: 'Roberto Castro',
    tenantName: 'Roberto Castro',
    monthlyFee: 180000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 9,
    unitId: 9,
    number: '101',
    buildingId: 3,
    floor: 1,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Patricia Morales',
    ownerEmail: 'patricia.morales@email.com',
    ownerPhone: '+56911112222',
    resident: 'Patricia Morales',
    tenantName: 'Patricia Morales',
    monthlyFee: 160000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 10,
    unitId: 10,
    number: '102',
    buildingId: 3,
    floor: 1,
    status: 'available',
    occupancyStatus: 'available',
    monthlyFee: 160000,
    pendingMonths: 0,
    balance: 0,
  },
  {
    id: 11,
    unitId: 11,
    number: '201',
    buildingId: 3,
    floor: 2,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Diego Vargas',
    ownerEmail: 'diego.vargas@email.com',
    ownerPhone: '+56999887766',
    resident: 'Diego Vargas',
    tenantName: 'Diego Vargas',
    monthlyFee: 160000,
    pendingMonths: 1,
    balance: -160000,
  },
  {
    id: 12,
    unitId: 12,
    number: '202',
    buildingId: 3,
    floor: 2,
    status: 'occupied',
    occupancyStatus: 'occupied',
    ownerName: 'Sofía Rojas',
    ownerEmail: 'sofia.rojas@email.com',
    ownerPhone: '+56988776655',
    resident: 'Sofía Rojas',
    tenantName: 'Sofía Rojas',
    monthlyFee: 160000,
    pendingMonths: 0,
    balance: 0,
  },
];

export const MOCK_LOGBOOK = [
  {
    id: 1,
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    note: 'Ingreso proveedor CCTV',
    createdBy: 'Juan Pérez',
    building: 'Torre Norte',
  },
  {
    id: 2,
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    note: 'Paquete Amazon Depto 305',
    createdBy: 'María Ruiz',
    building: 'Torre Central',
  },
  {
    id: 3,
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    note: 'Reparación ascensor completada',
    createdBy: 'Técnico Mantenimiento',
    building: 'Torre Sur',
  },
  {
    id: 4,
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    note: 'Revisión de seguridad área común',
    createdBy: 'Inspector',
    building: 'Torre Norte',
  },
];

export const MOCK_PACKAGES = [
  {
    id: 1,
    reference: 'Amazon #1234',
    trackingNumber: 'AMZN-2025-001',
    provider: 'Amazon',
    status: 'received',
    receivedAt: new Date(Date.now() - 86400000).toISOString(),
    deliveredAt: null,
    description: 'Paquete de electrónica',
  },
  {
    id: 2,
    reference: 'FedEx #8421',
    trackingNumber: 'FDX-2025-042',
    provider: 'FedEx',
    status: 'delivered',
    receivedAt: new Date(Date.now() - 172800000).toISOString(),
    deliveredAt: new Date(Date.now() - 86400000).toISOString(),
    description: 'Documento importante',
  },
  {
    id: 3,
    reference: 'DHL #5678',
    trackingNumber: 'DHL-2025-567',
    provider: 'DHL',
    status: 'pending',
    receivedAt: null,
    deliveredAt: null,
    description: 'Encomienda en tránsito',
  },
];

export const MOCK_AMENITIES = [
  {
    id: 1,
    name: 'Salón de reuniones',
    description: 'Salón multiusos con capacidad para 20 personas',
    capacity: 20,
    floor: 2,
    building: 'Torre Central',
  },
  {
    id: 2,
    name: 'Gym',
    description: 'Gimnasio completamente equipado',
    capacity: 15,
    floor: 1,
    building: 'Torre Norte',
  },
  {
    id: 3,
    name: 'Piscina',
    description: 'Piscina climatizada',
    capacity: 30,
    floor: 'Azotea',
    building: 'Torre Sur',
  },
  {
    id: 4,
    name: 'Cine',
    description: 'Sala de cine con pantalla 4K',
    capacity: 25,
    floor: 'Sótano 2',
    building: 'Torre Central',
  },
];

export const MOCK_VISITORS = [
  {
    id: 1,
    name: 'Pedro Martínez',
    email: 'pedro@example.com',
    phone: '+1234567895',
    unit: '305',
    building: 'Torre Central',
    invitationDate: new Date(Date.now() - 86400000).toISOString(),
    status: 'approved',
  },
  {
    id: 2,
    name: 'Ana García',
    email: 'ana@example.com',
    phone: '+1234567896',
    unit: '512',
    building: 'Torre Norte',
    invitationDate: new Date(Date.now() - 172800000).toISOString(),
    status: 'pending',
  },
];

export const MOCK_ASSETS = [
  {
    id: 1,
    name: 'Generador Diésel',
    type: 'Mechanical',
    location: 'Sótano 1',
    building: 'Torre Central',
    status: 'operational',
    lastMaintenance: '2025-11-15',
    nextMaintenance: '2026-02-15',
    serialNumber: 'GEN-2024-001',
  },
  {
    id: 2,
    name: 'Bomba de Agua',
    type: 'Mechanical',
    location: 'Azotea',
    building: 'Torre Norte',
    status: 'maintenance',
    lastMaintenance: '2025-10-20',
    nextMaintenance: '2025-12-20',
    serialNumber: 'PUMP-2024-002',
  },
  {
    id: 3,
    name: 'Ascensor Principal',
    type: 'Elevator',
    location: 'Lobby',
    building: 'Torre Central',
    status: 'operational',
    lastMaintenance: '2025-12-01',
    nextMaintenance: '2026-03-01',
    serialNumber: 'ELV-2024-001',
  },
  {
    id: 4,
    name: 'Sistema de Climatización',
    type: 'HVAC',
    location: 'Azotea',
    building: 'Torre Sur',
    status: 'operational',
    lastMaintenance: '2025-11-10',
    nextMaintenance: '2026-02-10',
    serialNumber: 'HVAC-2024-003',
  },
];

export const MOCK_ACCESS_LOGS = [
  {
    id: 1,
    residentId: 3,
    name: 'Resident One',
    unit: '305',
    type: 'entry',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    method: 'card',
    door: 'Main Entrance',
  },
  {
    id: 2,
    residentId: 3,
    name: 'Resident One',
    unit: '305',
    type: 'exit',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    method: 'card',
    door: 'Main Entrance',
  },
  {
    id: 3,
    residentId: 3,
    name: 'Resident One',
    unit: '305',
    type: 'entry',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    method: 'facial_recognition',
    door: 'Side Entrance',
  },
  {
    id: 4,
    residentId: 3,
    name: 'Resident One',
    unit: '305',
    type: 'exit',
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    method: 'code',
    door: 'Garage Entrance',
  },
  {
    id: 5,
    residentId: 3,
    name: 'Resident One',
    unit: '305',
    type: 'denied',
    timestamp: new Date(Date.now() - 259200000).toISOString(),
    method: 'card',
    door: 'Executive Floor',
    reason: 'Access not authorized for this door',
  },
];

export const MOCK_FINANCE = [
  {
    id: 1,
    month: 'November 2025',
    income: 45000,
    expenses: 28000,
    maintenance: 12000,
    utilities: 16000,
    balance: 17000,
  },
  {
    id: 2,
    month: 'October 2025',
    income: 45000,
    expenses: 30000,
    maintenance: 14000,
    utilities: 16000,
    balance: 15000,
  },
  {
    id: 3,
    month: 'September 2025',
    income: 44000,
    expenses: 27500,
    maintenance: 11000,
    utilities: 16500,
    balance: 16500,
  },
];

export const MOCK_MAINTENANCE_TICKETS = [
  {
    id: 1,
    title: 'Reparación de ascensor',
    description: 'El ascensor principal no responde correctamente',
    assetId: 3,
    priority: 'high',
    status: 'pending',
    reportedBy: 'admin@lobbysync.com',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 2,
    title: 'Limpieza de filtros HVAC',
    description: 'Cambio de filtros en sistema de climatización',
    assetId: 4,
    priority: 'medium',
    status: 'in_progress',
    reportedBy: 'concierge@lobbysync.com',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 3,
    title: 'Revisión de bomba de agua',
    description: 'Mantenimiento preventivo de la bomba',
    assetId: 2,
    priority: 'medium',
    status: 'completed',
    reportedBy: 'admin@lobbysync.com',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const MOCK_LOGIN_RESPONSE = {
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBsb2JieXN5bmMuY29tIiwicm9sZSI6IkFETUluIiwiZW1haWwiOiJhZG1pbkBsb2JieXN5bmMuY29tIiwiaWF0IjoxNjM0NTY3ODAwLCJleHAiOjE2MzQ2NTQyMDB9.EMP_TOKEN_FOR_TESTING',
  user: {
    email: 'admin@lobbysync.com',
    role: 'ADMIN',
    username: 'admin',
  },
};
